name: Manually Build Release
on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: "Version number of this release"
        required: true
        type: string
jobs:
  test-lint-scan:
    uses: ./.github/workflows/test_lint_scan.yml

  build_release:
    name: Build Release
    needs: test-lint-scan
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing to pypi
      id-token: write
      # This permissions is necessary for creating the GitHub release
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12
      - name: Build Release
        run: pdm build
        env:
          PDM_BUILD_SCM_VERSION: ${{ inputs.versionNumber }}
      - name: Publish Release
        run: pdm publish --no-build
      - name: Create GitHub Release
        run: gh release create v${{inputs.versionNumber}} --latest --generate-notes dist/*
