name: Manually Build Release
on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: "Version number of this release"
        required: true
        type: string
jobs:
  test-lint-scan:
    uses: ./.github/workflows/test_lint_scan.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build_release:
    name: Build Release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.11
      - name: Build Release
        run: pdm build
        env:
          PDM_BUILD_SCM_VERSION: ${{ inputs.versionNumber }}
      - name: Publish Release
        run: pdm publish --no-build
      - name: Create GitHub Release
        run: gh release create v${{inputs.versionNumber}} --latest --generate-notes dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}