name: Pull Requests
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  test-lint-scan:
    uses: ./.github/workflows/test_lint_scan.yml