name: Test - Lint - Scan
on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  test:
    name: Testing
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, "3.10", 3.11, 3.12]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pdm install -dG :all
      - name: Run Testing
        run: |
          pdm run -v testing

  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pdm install -dG :all --no-self
      - name: Run Linting
        run: |
          pdm run -v lint-full

  scan:
    name: Scanning
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pdm install -dG :all --no-self
          # Set the `CODEQL-PYTHON` environment variable to the Python executable
          # that includes the dependencies
          echo "CODEQL_PYTHON=$(pdm info --python)" >> $GITHUB_ENV
      - name: Initialize Runtime Code Analysis
        uses: github/codeql-action/init@v3
        with:
          languages: python
      - name: Perform Runtime Code Analysis
        uses: github/codeql-action/analyze@v3
      - name: Perform Secure Code Analysis (Secrets)
        uses: trufflesecurity/trufflehog@main
